### ISSUE TITLE
Planificateur : afficher opérateur -> planifier

### ISSUE THREAD

**Issue by killiankopp** [cairnmanagement/planification#1]

**Comment by killiankopp** [comment]
**customer and user**
FE - chargés d'affaires / conducteurs de travaux

**Scrum brief**
En tant que planificateur, je veux afficher la liste des opérateurs (sous contrat et éventuellement hors contrat) afin de les planifier.

**Brief**
Pour permettre la planification, la première étape peut consister à afficher la liste du personnel et à prendre connaissance de la durée de leur contrat. Il peut aussi être intéressant d'afficher la liste du personnel qui a quitté l'entreprise pour les rappeler et leur proposer de travailler à nouveau pour nous.

**Additional information**

**Team**
@killiankopp 

**Code indication**

**Todo**
- [ ] @heligonSeb : créer l'app et la mettre sur Github
- [ ] @heligonSeb : afficher la liste du personnel et le planning tel que dans la V1
- [ ] @heligonSeb : permettre l'affichage du personnel hors contrat
- [ ] @heligonSeb : lister les routes nécessaires + spécifications
- [ ] @killiankopp : créer ou modifier les routes si nécessaire
