### ISSUE TITLE
Planificateur : filtrer par métier -> chercher rapidement un opérateur pour un besoin

### ISSUE THREAD

**Issue by killiankopp** [cairnmanagement/planification#2]

**Comment by killiankopp** [comment]
**customer and user**
FE - chargés affaires

**Scrum brief**
En tant que planificateur, je veux filtrer la liste par métier afin de trouver un opérateur correspondant à un besoin. Ex : un APLAM sur la période du tant au tant.

**Brief**
Les opérateurs ont plusieurs métiers. Les métiers sont issus des habilitations et des attestations. Il faut donc créer une table intermédiaire et prévoir sa mise à jour afin de pouvoir connaître en temps réel les métiers des opérateurs. 

**Additional information**

**Team**
@killiankopp 

**Code indication**

**Todo**
- [ ] @heligonSeb : proposer les tables nécessaires 
- [ ] @heligonSeb : créer les umls
- [ ] @heligonSeb : créer les tables
- [ ] @killiankopp  : remplir les tables
- [ ] @heligonSeb : faire un point sur les routes et écrire les spécifications de celles manquantes
- [ ] @killiankopp  : créer les routes
- [ ] @heligonSeb : ajouter le filtre sur la vue
